### DISCUSSION TITLE
`Nginx-Cloudflare`设置HTTPS抛出` The read operation timed out`

### DISCUSSION THREAD

**Discussion by despire1119** [encode/httpx#3152] [Q&A]
大佬我又来了，我在以HTTPS模式设置的过程中抛出` The read operation timed out`，请问这是我证书问题吗？我申请的Cloudflare 15年的免费证书，需要在我的服务端怎么配置呢？log如下：
```
[+] Running 1/0
 ✔ Container nginx-cloudflare-natter-nginx-cf-1  Created                                                            0.0s 
Attaching to natter-nginx-cf-1
natter-nginx-cf-1  | 2024-03-23 12:46:06 [I] Natter v2.0.0-rc3
natter-nginx-cf-1  | 2024-03-23 12:46:10 [I] 
natter-nginx-cf-1  | 2024-03-23 12:46:10 [I] tcp://192.168.1.105:2334 <--iptables--> tcp://192.168.1.105:34127 <--Natter--> tcp://223.65.118.12:3169
natter-nginx-cf-1  | 2024-03-23 12:46:10 [I] 
natter-nginx-cf-1  | 2024-03-23 12:46:10 [I] Calling script: /opt/cf-redir.py
natter-nginx-cf-1  | Setting [ nas.letscoding.fun ] DNS to [ 223.65.118.12 ] proxied by CloudFlare...
natter-nginx-cf-1  | Traceback (most recent call last):
natter-nginx-cf-1  |   File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
natter-nginx-cf-1  |     h.request(req.get_method(), req.selector, req.data, headers,
natter-nginx-cf-1  |   File "/usr/lib/python3.11/http/client.py", line 1282, in request
natter-nginx-cf-1  |     self._send_request(method, url, body, headers, encode_chunked)
natter-nginx-cf-1  |   File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
natter-nginx-cf-1  |     self.endheaders(body, encode_chunked=encode_chunked)
natter-nginx-cf-1  |   File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
natter-nginx-cf-1  |     self._send_output(message_body, encode_chunked=encode_chunked)
natter-nginx-cf-1  |   File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
natter-nginx-cf-1  |     self.send(msg)
natter-nginx-cf-1  |   File "/usr/lib/python3.11/http/client.py", line 975, in send
natter-nginx-cf-1  |     self.connect()
natter-nginx-cf-1  |   File "/usr/lib/python3.11/http/client.py", line 1454, in connect
natter-nginx-cf-1  |     self.sock = self._context.wrap_socket(self.sock,
natter-nginx-cf-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
natter-nginx-cf-1  |   File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
natter-nginx-cf-1  |     return self.sslsocket_class._create(
natter-nginx-cf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
natter-nginx-cf-1  |   File "/usr/lib/python3.11/ssl.py", line 1075, in _create
natter-nginx-cf-1  |     self.do_handshake()
natter-nginx-cf-1  |   File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
natter-nginx-cf-1  |     self._sslobj.do_handshake()
natter-nginx-cf-1  | TimeoutError: _ssl.c:975: The handshake operation timed out
natter-nginx-cf-1  | 
natter-nginx-cf-1  | During handling of the above exception, another exception occurred:
natter-nginx-cf-1  | 
natter-nginx-cf-1  | Traceback (most recent call last):
natter-nginx-cf-1  |   File "/opt/cf-redir.py", line 228, in <module>
natter-nginx-cf-1  |     main()
natter-nginx-cf-1  |   File "/opt/cf-redir.py", line 20, in main
natter-nginx-cf-1  |     cf.set_a_record(cf_redirect_host, public_ip, proxied=True)
natter-nginx-cf-1  |   File "/opt/cf-redir.py", line 39, in set_a_record
natter-nginx-cf-1  |     zone_id = self._find_zone_id(name)
natter-nginx-cf-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^
natter-nginx-cf-1  |   File "/opt/cf-redir.py", line 79, in _find_zone_id
natter-nginx-cf-1  |     data = self._url_req(
natter-nginx-cf-1  |            ^^^^^^^^^^^^^^
natter-nginx-cf-1  |   File "/opt/cf-redir.py", line 67, in _url_req
natter-nginx-cf-1  |     with self.opener.open(req, timeout=10) as res:
natter-nginx-cf-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
natter-nginx-cf-1  |   File "/usr/lib/python3.11/urllib/request.py", line 519, in open
natter-nginx-cf-1  |     response = self._open(req, data)
natter-nginx-cf-1  |                ^^^^^^^^^^^^^^^^^^^^^
natter-nginx-cf-1  |   File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
natter-nginx-cf-1  |     result = self._call_chain(self.handle_open, protocol, protocol +
natter-nginx-cf-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
natter-nginx-cf-1  |   File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
natter-nginx-cf-1  |     result = func(*args)
natter-nginx-cf-1  |              ^^^^^^^^^^^
natter-nginx-cf-1  |   File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
natter-nginx-cf-1  |     return self.do_open(http.client.HTTPSConnection, req,
natter-nginx-cf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
natter-nginx-cf-1  |   File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
natter-nginx-cf-1  |     raise URLError(err)
natter-nginx-cf-1  | urllib.error.URLError: <urlopen error _ssl.c:975: The handshake operation timed out>
natter-nginx-cf-1  | 2024-03-23 12:46:20 [I] LAN > 192.168.1.105:2334    [ OPEN ]
natter-nginx-cf-1  | 2024-03-23 12:46:20 [I] LAN > 192.168.1.105:34127   [ OPEN ]
natter-nginx-cf-1  | 2024-03-23 12:46:20 [I] LAN > 223.65.118.12:3169    [ OPEN ]
natter-nginx-cf-1  | 2024-03-23 12:46:27 [I] WAN > 223.65.118.12:3169    [ OPEN ]
natter-nginx-cf-1  | 2024-03-23 12:46:27 [I] 
```
`yml`配置:
```
version: "3"
services:
  natter-nginx-cf:
    command: -m iptables -e /opt/cf-redir.py -p 2334
    # command: -e /opt/cf-redir.py -p 2333
    volumes:
      - ./cf-redir.py:/opt/cf-redir.py
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    image: nattertool/natter:latest
    restart: always
  #   depends_on:
  #     - nginx

  # nginx:
  #   volumes:
  #     - ./html:/usr/share/nginx/html
  #   ports:
  #     - "18888:80"
  #   environment:
  #     - TZ=Asia/Shanghai
  #   image: nginx
  #   restart: always

```
