### DISCUSSION TITLE
Install httpx without pulling anyio, trio and socks

### DISCUSSION THREAD

**Discussion by tbarbugli** [encode/httpx#3182] [General]
I have these dependencies installed with Poetry

```toml
[tool.poetry.dependencies]
python = ">=3.8.1,<4.0.0"
httpx = "^0.27.0"
```

This adds additional dependencies such as anyio, trio and socks that I am not using in the project. Unfortunately these dependencies come from httpx's httpcore dependency.

Is there a way to only get httpcore with no additional async libs?
